import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { App } from '../src/App.jsx';
import { SignInPage } from '../src/pages/SignInPage.jsx';
import { LandingPage } from '../src/pages/LandingPage.jsx';
import { DashboardPage } from '../src/pages/DashboardPage.jsx';
import { ZoneAnalysisPage } from '../src/pages/ZoneAnalysisPage.jsx';
import { MovementPage } from '../src/pages/MovementPage.jsx';
import { InsightsPage } from '../src/pages/InsightsPage.jsx';
import { FeaturesPage } from '../src/pages/FeaturesPage.jsx';
import { HowItWorksPage } from '../src/pages/HowItWorksPage.jsx';
import { PrivacyPage } from '../src/pages/PrivacyPage.jsx';
import { Navigation } from '../src/components/Navigation.jsx';
import { Footer } from '../src/components/Footer';

// Mock active analysis generated by the real CV pipeline
const sampleRealAnalysis = {
  analysis_id: "AN_TEST_123456",
  video_metadata: {
    filename: "demo.mp4",
    width: 1920,
    height: 1080,
    fps: 30.0,
    total_frames: 569,
    duration_seconds: 18.97,
    duration_formatted: "00:18",
    file_size_mb: 14.76
  },
  total_unique_tracks: 44,
  peak_occupancy: 13,
  average_occupancy: 7.05,
  occupancy_timeline: [
    { timestamp: 0.0, occupancy: 2 },
    { timestamp: 1.0, occupancy: 5 }
  ],
  dwell_time: {
    average_seconds: 8.4,
    average_formatted: "8s",
    max_seconds: 18.2,
    max_formatted: "18s"
  },
  zones: [
    {
      id: "zone_a",
      name: "Zone A - Northwest Concourse",
      x: 5, y: 5, width: 42, height: 42,
      color: "#6C4AB6",
      visitors: 12,
      points_count: 54,
      density_pct: 35.5,
      dwellAvg: 6.2,
      dwellAvg_formatted: "6s",
      status: "High Traffic"
    },
    {
      id: "zone_b",
      name: "Zone B - Northeast Gallery",
      x: 53, y: 5, width: 42, height: 42,
      color: "#4ECCA3",
      visitors: 4,
      points_count: 18,
      density_pct: 12.0,
      dwellAvg: 4.1,
      dwellAvg_formatted: "4s",
      status: "Moderate Flow"
    }
  ],
  trajectories: [
    {
      track_id: 1,
      label: "Person Track #1",
      dwell_time_seconds: 7.2,
      dwell_formatted: "7s",
      points: [[20, 30], [25, 35], [30, 40]]
    }
  ],
  heatmap: Array(50).fill(Array(50).fill(0)),
  traffic_analysis: {
    highest_traffic_zone: "Zone A - Northwest Concourse",
    lowest_traffic_zone: "Zone B - Northeast Gallery",
    highest_traffic_density_pct: 35.5,
    lowest_traffic_density_pct: 12.0,
    congestion_status: "Moderate",
    explanation: "Highest traffic concentrated in Zone A."
  },
  insights: [
    {
      id: "ins-traffic",
      type: "traffic",
      title: "Primary Circulation Hub: Zone A",
      description: "Concentrated 35.5% of movement.",
      impact: "High Traffic (35.5%)"
    }
  ],
  processing_time_seconds: 4.87,
  model_information: "Ultralytics YOLOv8n + ByteTrack"
};

console.log("=================================================");
console.log("RUNNING SHENEX COMPONENT & ROUTING VALIDATION");
console.log("=================================================");

let passCount = 0;
let failCount = 0;

function assert(condition, name, actual = "") {
  if (condition) {
    console.log(`[PASS] ${name}`);
    passCount++;
  } else {
    console.error(`[FAIL] ${name}`);
    if (actual) console.error(`  -> Rendered snippet: ${actual.slice(0, 200)}...`);
    failCount++;
  }
}

try {
  // Test 1: SignInPage renders properly
  const htmlSignIn = ReactDOMServer.renderToString(
    React.createElement(SignInPage, { onAuthSuccess: () => {} })
  );
  assert(htmlSignIn.includes("Sign in to continue") && htmlSignIn.includes("Username"), "SignInPage renders login form");
  assert(!htmlSignIn.includes("History"), "SignInPage has NO History");

  // Test 2: LandingPage renders the exact preserved SHENEX Hero & branding
  const htmlLanding = ReactDOMServer.renderToString(
    React.createElement(LandingPage, { onNavigate: () => {}, onSelectPreset: () => {} })
  );
  assert(htmlLanding.includes("See the Space") && htmlLanding.includes("Understand the Movement"), "LandingPage preserves exact 'See the Space. Understand the Movement.' hero");
  assert(htmlLanding.includes("Occupancy Intelligence") && htmlLanding.includes("Spatial Heatmaps"), "LandingPage preserves core feature cards");
  assert(!htmlLanding.includes("History"), "LandingPage has NO History");

  // Test 3: Navigation renders Home, Features, How It Works, Privacy, Dashboard, Upload Video (NO History)
  const mockUser = { id: "u123", username: "analyst_demo" };
  const htmlNav = ReactDOMServer.renderToString(
    React.createElement(Navigation, {
      currentPage: "dashboard",
      onNavigate: () => {},
      currentUser: mockUser,
      onLogout: () => {},
      hasActiveAnalysis: true
    })
  );
  assert(htmlNav.includes("Home") && htmlNav.includes("Features") && htmlNav.includes("How It Works") && htmlNav.includes("Privacy") && htmlNav.includes("Dashboard"), "Navigation renders all original SHENEX links");
  assert(htmlNav.includes("analyst_demo"), "Navigation renders current user badge", htmlNav);
  assert(!htmlNav.includes("History") && !htmlNav.includes("history"), "Navigation has NO History link anywhere", htmlNav);

  // Test 4: DashboardPage empty state
  const htmlDashEmpty = ReactDOMServer.renderToString(
    React.createElement(DashboardPage, {
      activeAnalysis: null,
      onClearAnalysis: () => {},
      onNavigate: () => {}
    })
  );
  assert(htmlDashEmpty.includes("Your space is waiting") && htmlDashEmpty.includes("Upload Video"), "Dashboard renders clean empty state when no video analyzed", htmlDashEmpty);

  // Test 5: DashboardPage with real analysis (shows 4 tabs: Overview, Zone Analysis, Movement Flow, AI Insights)
  const htmlDashActive = ReactDOMServer.renderToString(
    React.createElement(DashboardPage, {
      activeAnalysis: sampleRealAnalysis,
      onClearAnalysis: () => {},
      onNavigate: () => {}
    })
  );
  assert(htmlDashActive.includes("AN_TEST_123456") && htmlDashActive.includes("44"), "Dashboard renders real analysis payload", htmlDashActive);
  assert(htmlDashActive.includes("Overview") && htmlDashActive.includes("Zone Analysis") && htmlDashActive.includes("Movement Flow") && htmlDashActive.includes("AI Insights"), "Dashboard renders the 4 analysis sub-tabs");

  // Test 6: ZoneAnalysisPage empty state (NO crash, NO black page)
  const htmlZoneEmpty = ReactDOMServer.renderToString(
    React.createElement(ZoneAnalysisPage, {
      currentPreset: null,
      onNavigate: () => {}
    })
  );
  assert(htmlZoneEmpty.includes("No video analyzed yet") && htmlZoneEmpty.includes("Upload Video"), "ZoneAnalysisPage renders clean empty state (NO black/blank screen)", htmlZoneEmpty);

  // Test 7: ZoneAnalysisPage with real analysis (NO TypeError on preset.stats)
  const htmlZoneActive = ReactDOMServer.renderToString(
    React.createElement(ZoneAnalysisPage, {
      currentPreset: sampleRealAnalysis,
      onNavigate: () => {}
    })
  );
  assert(htmlZoneActive.includes("Zone A - Northwest Concourse") && htmlZoneActive.includes("Traffic Analysis"), "ZoneAnalysisPage renders real zones table without crashing", htmlZoneActive);

  // Test 8: MovementPage empty state
  const htmlMoveEmpty = ReactDOMServer.renderToString(
    React.createElement(MovementPage, {
      currentPreset: null,
      onNavigate: () => {}
    })
  );
  assert(htmlMoveEmpty.includes("No video analyzed yet") && htmlMoveEmpty.includes("Upload Video"), "MovementPage renders clean empty state", htmlMoveEmpty);

  // Test 9: MovementPage with real analysis
  const htmlMoveActive = ReactDOMServer.renderToString(
    React.createElement(MovementPage, {
      currentPreset: sampleRealAnalysis,
      onNavigate: () => {}
    })
  );
  assert(htmlMoveActive.includes("Movement Patterns"), "MovementPage renders real trajectories without crashing", htmlMoveActive);

  // Test 10: InsightsPage empty state (NO crash, NO black page)
  const htmlInsightEmpty = ReactDOMServer.renderToString(
    React.createElement(InsightsPage, {
      currentPreset: null,
      onNavigate: () => {}
    })
  );
  assert(htmlInsightEmpty.includes("No video analyzed yet") && htmlInsightEmpty.includes("Upload Video"), "InsightsPage renders clean empty state (NO black/blank screen)", htmlInsightEmpty);

  // Test 11: InsightsPage with real analysis (NO TypeError on preset.stats.congestionIndex)
  const htmlInsightActive = ReactDOMServer.renderToString(
    React.createElement(InsightsPage, {
      currentPreset: sampleRealAnalysis,
      onNavigate: () => {}
    })
  );
  assert(htmlInsightActive.includes("AI Spatial Insights") && htmlInsightActive.includes("Primary Circulation Hub: Zone A"), "InsightsPage renders real insights without crashing", htmlInsightActive);

  // Test 12: Content Pages (Features, HowItWorks, Privacy) render properly
  const htmlFeatures = ReactDOMServer.renderToString(React.createElement(FeaturesPage, { onNavigate: () => {} }));
  // Test 13: Full App render when unauthenticated -> Sign-In appears FIRST!
  const htmlAppLoggedOut = ReactDOMServer.renderToString(React.createElement(App));
  assert(htmlAppLoggedOut.includes("Sign in to continue") && htmlAppLoggedOut.includes("Username"), "App renders Sign-In FIRST when logged out");
  assert(!htmlAppLoggedOut.includes("See the Space") && !htmlAppLoggedOut.includes("Analytics Dashboard"), "App hides Home, Dashboard, and Analysis before login");

  console.log("-------------------------------------------------");
  console.log(`TOTAL TESTS: ${passCount + failCount} | PASSED: ${passCount} | FAILED: ${failCount}`);
  if (failCount === 0) {
    console.log("ALL SHENEX ARCHITECTURE & AUTHENTICATION TESTS PASSED 100%!");
  } else {
    process.exit(1);
  }
} catch (e) {
  console.error("Test execution threw error:", e);
  process.exit(1);
}
